version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: digital_wallet
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 2vPKNZ8PgF321QFyzQ
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: .Dockerfile
    container_name: digitalwallet_api
    restart: always
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"

volumes:
  postgres_data: